version: '3'

services:

    jump:
        image: daledavies/jump
        ports:
            - "8200:8080"
        volumes:
            - ./jump/backgrounds:/backgrounds
            - ./jump/favicon:/favicon
            - ./jump/search:/search
            - ./jump/sites:/sites
        environment:
            SITENAME: 'Jump Dashboard'
            OWMAPIKEY: ''                           # Poner datos correctos API key de Open Weather Map 
            LATLONG: ''                             # Poner datos correctos LAT y LONG
            SHOWCLOCK: 'true'
            AMPMCLOCK: 'false'
            SHOWGREETING: 'false'
            METRICTEMP: 'true'
            CACHEBYPASS: 'true'
            CHECKSTATUS: 'true'

            
