version: '3'

services:

    jump:
        image: daledavies/jump
        ports:
            - "8200:8080"
        volumes:
            - ./jump/backgrounds:/backgrounds
            - ./jump/favicon:/favicon
            - ./jump/search:/search
            - ./jump/sites:/sites
        environment:
            SITENAME: 'Jump Dashboard'
#            OWMAPIKEY: '0a1b2c3d4e5f6a7b8c9d0a1b'  # Poner datos correctos
#            LATLONG: '51.509865,-0.118092'         # Poner datos correctos
            SHOWCLOCK: 'true'
            AMPMCLOCK: 'false'
            SHOWGREETING: 'false'
            METRICTEMP: 'true'
            CACHEBYPASS: 'true'
            CHECKSTATUS: 'true'

            
